<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Api_get_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    function get_data_barang()
    {
        $this->db->select('b.id,b.cabang_id,b.produk_id,b.nama,b.detail,b.harga,b.foto');
        $this->db->select('p.kategori_id');
        // $this->db->select('');
        $this->db->from('barang AS b');
        // $this->db->order_by('close', 'DESC');
        $this->db->join('produk AS p', 'p.id = b.produk_id');
        // $this->db->join('pegawai', 'pegawai.id = responsible.pegawai_id');
        // $this->db->join('cabang', 'cabang.id = responsible.cabang_id');
        // $this->db->where('pegawai.username', $this->input->post("username"));
        $query =  $this->db->get();
        return $query->result_array();
    }
}
